/**
 * @jest-environment node
 */

import { POST as postPoints } from './points/route'
import { POST as postWKT } from './wkt/route'
import { expectRfc7946FeatureCollection } from '../test-utils/geojsonAssertions'

const hasPostgresCredentials = Boolean(
  process.env.POSTGRES_URL ||
    process.env.POSTGRES_PRISMA_URL ||
    process.env.POSTGRES_URL_NON_POOLING ||
    process.env.DATABASE_URL
)

const describeWithPostgres = hasPostgresCredentials ? describe : describe.skip

function jsonRequest(url: string, body: unknown) {
  return new Request(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  })
}

describeWithPostgres('GeoJSON API PostGIS integration', () => {
  it('returns RFC 7946 point features generated by PostGIS', async () => {
    const request = jsonRequest('http://localhost:3000/api/geojson/points', {
      data: [
        {
          name: 'Kansas City',
          lat: 39.0997,
          lng: -94.5786,
          population: 508090,
          ignored: 'not requested',
        },
        {
          name: 'St. Louis',
          lat: 38.627,
          lng: -90.1994,
          population: 301578,
          ignored: 'not requested',
        },
      ],
      latField: 'lat',
      lngField: 'lng',
      properties: ['name', 'population'],
    })

    const response = await postPoints(request as any)
    const geojson = await response.json()

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(geojson)
    expect(geojson).toEqual({
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [-94.5786, 39.0997],
          },
          properties: {
            name: 'Kansas City',
            population: 508090,
          },
        },
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [-90.1994, 38.627],
          },
          properties: {
            name: 'St. Louis',
            population: 301578,
          },
        },
      ],
    })
  })

  it('returns RFC 7946 geometries converted from WKT by PostGIS', async () => {
    const request = jsonRequest('http://localhost:3000/api/geojson/wkt', {
      data: [
        {
          name: 'Central Park',
          wkt: 'POLYGON((-73.9654 40.7829, -73.9654 40.8012, -73.9497 40.8012, -73.9497 40.7829, -73.9654 40.7829))',
          area: 843,
        },
        {
          name: 'Times Square',
          wkt: 'POINT(-73.9855 40.7580)',
          area: null,
        },
      ],
      wktField: 'wkt',
      properties: ['name', 'area'],
    })

    const response = await postWKT(request as any)
    const geojson = await response.json()

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(geojson)
    expect(geojson).toEqual({
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [-73.9654, 40.7829],
                [-73.9654, 40.8012],
                [-73.9497, 40.8012],
                [-73.9497, 40.7829],
                [-73.9654, 40.7829],
              ],
            ],
          },
          properties: {
            name: 'Central Park',
            area: 843,
          },
        },
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [-73.9855, 40.758],
          },
          properties: {
            name: 'Times Square',
            area: null,
          },
        },
      ],
    })
  })
})
