import { POST } from './route'
import { sql } from '@vercel/postgres'
import { expectRfc7946FeatureCollection } from '../../test-utils/geojsonAssertions'

jest.mock('@vercel/postgres', () => ({
  sql: jest.fn(),
}))

jest.mock('next/server', () => ({
  NextResponse: {
    json: jest.fn((data, options) => ({
      json: () => Promise.resolve(data),
      status: options?.status || 200,
    })),
  },
}))

describe('GeoJSON WKT API', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('should return an RFC 7946 FeatureCollection generated by PostGIS', async () => {
    const geojson = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [-73.9654, 40.7829],
                [-73.9654, 40.8012],
                [-73.9497, 40.8012],
                [-73.9497, 40.7829],
                [-73.9654, 40.7829],
              ],
            ],
          },
          properties: {
            name: 'Central Park',
          },
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/wkt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [
          {
            name: 'Central Park',
            wkt: 'POLYGON((-73.9654 40.7829, -73.9654 40.8012, -73.9497 40.8012, -73.9497 40.7829, -73.9654 40.7829))',
          },
        ],
        wktField: 'wkt',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()
    const sqlCall = (sql as unknown as jest.Mock).mock.calls[0]
    const sqlText = sqlCall[0].join(' ')

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(data)
    expect(sqlText).toContain('generate_geojson')
    expect(sqlCall.slice(1)).toEqual([
      JSON.stringify([
        {
          name: 'Central Park',
          wkt: 'POLYGON((-73.9654 40.7829, -73.9654 40.8012, -73.9497 40.8012, -73.9497 40.7829, -73.9654 40.7829))',
        },
      ]),
      'wkt',
      ['name'],
    ])
  })

  it('should accept RFC 7946 null properties generated by PostGIS', async () => {
    const geojson = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [-73.9855, 40.758],
          },
          properties: null,
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/wkt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ wkt: 'POINT(-73.9855 40.7580)' }],
        wktField: 'wkt',
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(data)
    expect(data.features[0].properties).toBeNull()
  })

  it('should reject non-RFC 7946 GeoJSON generated by PostGIS', async () => {
    const consoleError = jest
      .spyOn(console, 'error')
      .mockImplementation(() => undefined)
    const geojson = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [-73.9654, 40.7829],
                [-73.9654, 40.8012],
                [-73.9497, 40.8012],
                [-73.9497, 40.7829],
              ],
            ],
          },
          properties: {
            name: 'Open polygon',
          },
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/wkt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [
          {
            name: 'Open polygon',
            wkt: 'POLYGON((-73.9654 40.7829, -73.9654 40.8012, -73.9497 40.8012, -73.9497 40.7829, -73.9654 40.7829))',
          },
        ],
        wktField: 'wkt',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(500)
    expect(data).toEqual({
      error: 'Invalid GeoJSON generated by PostGIS',
      errors: [
        {
          field: 'features[0].geometry.coordinates[0]',
          message: 'linear ring must start and end with the same position',
        },
      ],
    })
    consoleError.mockRestore()
  })

  it('should reject invalid WKT before PostGIS conversion', async () => {
    const request = new Request('http://localhost:3000/api/geojson/wkt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ name: 'Invalid', wkt: 'NOT_A_GEOMETRY(0 0)' }],
        wktField: 'wkt',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(400)
    expect(data).toEqual({
      error: 'Validation error occurred',
      errors: [
        {
          field: 'data[0].wkt',
          message: 'wkt must be a valid WKT geometry string',
        },
      ],
    })
    expect(sql as unknown as jest.Mock).not.toHaveBeenCalled()
  })

  it('should reject empty WKT datasets before PostGIS conversion', async () => {
    const request = new Request('http://localhost:3000/api/geojson/wkt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [],
        wktField: 'wkt',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(400)
    expect(data).toEqual({
      error: 'Validation error occurred',
      errors: [
        {
          field: 'data',
          message: 'data must be a non-empty array',
        },
      ],
    })
    expect(sql as unknown as jest.Mock).not.toHaveBeenCalled()
  })
})
