import { POST } from './route'
import { sql } from '@vercel/postgres'

jest.mock('@vercel/postgres', () => ({
  sql: jest.fn(),
}))

jest.mock('next/server', () => ({
  NextResponse: {
    json: jest.fn((data, options) => ({
      json: () => Promise.resolve(data),
      status: options?.status || 200,
    })),
  },
}))

function expectPositions(coordinates: unknown) {
  expect(Array.isArray(coordinates)).toBe(true)

  if (
    Array.isArray(coordinates) &&
    typeof coordinates[0] === 'number' &&
    typeof coordinates[1] === 'number'
  ) {
    const [longitude, latitude] = coordinates as number[]
    expect(longitude).toBeGreaterThanOrEqual(-180)
    expect(longitude).toBeLessThanOrEqual(180)
    expect(latitude).toBeGreaterThanOrEqual(-90)
    expect(latitude).toBeLessThanOrEqual(90)
    return
  }

  for (const child of coordinates as unknown[]) {
    expectPositions(child)
  }
})

function expectRfc7946FeatureCollection(geojson: any) {
  expect(geojson.type).toBe('FeatureCollection')
  expect(geojson.crs).toBeUndefined()
  expect(Array.isArray(geojson.features)).toBe(true)

  for (const feature of geojson.features) {
    expect(feature.type).toBe('Feature')
    expect(feature.geometry).toEqual(expect.any(Object))
    expectPositions(feature.geometry.coordinates)
    expect(feature.properties).toEqual(expect.any(Object))
  }
}

describe('GeoJSON WKT API', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('should return an RFC 7946 FeatureCollection generated by PostGIS', async () => {
    const geojson = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [-73.9654, 40.7829],
                [-73.9654, 40.8012],
                [-73.9497, 40.8012],
                [-73.9497, 40.7829],
                [-73.9654, 40.7829],
              ],
            ],
          },
          properties: {
            name: 'Central Park',
          },
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/wkt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [
          {
            name: 'Central Park',
            wkt: 'POLYGON((-73.9654 40.7829, -73.9654 40.8012, -73.9497 40.8012, -73.9497 40.7829, -73.9654 40.7829))',
          },
        ],
        wktField: 'wkt',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()
    const sqlCall = (sql as unknown as jest.Mock).mock.calls[0]
    const sqlText = sqlCall[0].join(' ')

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(data)
    expect(sqlText).toContain('generate_geojson')
    expect(sqlCall.slice(1)).toEqual([
      JSON.stringify([
        {
          name: 'Central Park',
          wkt: 'POLYGON((-73.9654 40.7829, -73.9654 40.8012, -73.9497 40.8012, -73.9497 40.7829, -73.9654 40.7829))',
        },
      ]),
      'wkt',
      ['name'],
    ])
  })

  it('should reject invalid WKT before PostGIS conversion', async () => {
    const request = new Request('http://localhost:3000/api/geojson/wkt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ name: 'Invalid', wkt: 'NOT_A_GEOMETRY(0 0)' }],
        wktField: 'wkt',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(400)
    expect(data).toEqual({
      error: 'Validation error occurred',
      errors: [
        {
          field: 'data[0].wkt',
          message: 'wkt must be a valid WKT geometry string',
        },
      ],
    })
    expect(sql as unknown as jest.Mock).not.toHaveBeenCalled()
  })
}
