import { POST } from './route'
import { sql } from '@vercel/postgres'
import { expectRfc7946FeatureCollection } from '../../test-utils/geojsonAssertions'

jest.mock('@vercel/postgres', () => ({
  sql: jest.fn(),
}))

jest.mock('next/server', () => ({
  NextResponse: {
    json: jest.fn((data, options) => ({
      json: () => Promise.resolve(data),
      status: options?.status || 200,
    })),
  },
}))

describe('GeoJSON Points API', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('should return an RFC 7946 FeatureCollection generated by PostGIS', async () => {
    const geojson = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [0, 0],
          },
          properties: {
            name: 'Null Island',
          },
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/points', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ name: 'Null Island', lat: 0, lng: 0 }],
        latField: 'lat',
        lngField: 'lng',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()
    const sqlCall = (sql as unknown as jest.Mock).mock.calls[0]
    const sqlText = sqlCall[0].join(' ')

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(data)
    expect(data.features[0].geometry.type).toBe('Point')
    expect(sqlText).toContain('generate_geojson')
    expect(sqlCall.slice(1)).toEqual([
      JSON.stringify([{ name: 'Null Island', lat: 0, lng: 0 }]),
      'lat',
      'lng',
      ['name'],
    ])
  })

  it('should accept RFC 7946 null properties generated by PostGIS', async () => {
    const geojson = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [-94.5786, 39.0997],
          },
          properties: null,
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/points', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ lat: 39.0997, lng: -94.5786 }],
        latField: 'lat',
        lngField: 'lng',
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(data)
    expect(data.features[0].properties).toBeNull()
  })

  it('should reject non-RFC 7946 GeoJSON generated by PostGIS', async () => {
    const consoleError = jest
      .spyOn(console, 'error')
      .mockImplementation(() => undefined)
    const geojson = {
      type: 'FeatureCollection',
      crs: {
        type: 'name',
        properties: { name: 'EPSG:3857' },
      },
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [-94.5786, 91],
          },
          properties: {
            name: 'Invalid latitude',
          },
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/points', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ name: 'Invalid latitude', lat: 0, lng: 0 }],
        latField: 'lat',
        lngField: 'lng',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(500)
    expect(data).toEqual({
      error: 'Invalid GeoJSON generated by PostGIS',
      errors: [
        {
          field: 'crs',
          message: 'crs member is not allowed in RFC 7946 GeoJSON',
        },
        {
          field: 'features[0].geometry.coordinates[1]',
          message: 'latitude must be between -90 and 90 degrees',
        },
      ],
    })
    consoleError.mockRestore()
  })

  it('should reject point coordinates outside RFC 7946 bounds before PostGIS', async () => {
    const request = new Request('http://localhost:3000/api/geojson/points', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ name: 'Invalid', lat: 91, lng: 181 }],
        latField: 'lat',
        lngField: 'lng',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(400)
    expect(data).toEqual({
      error: 'Validation error occurred',
      errors: [
        {
          field: 'data[0].lat',
          message: 'lat must be between -90 and 90 degrees',
        },
        {
          field: 'data[0].lng',
          message: 'lng must be between -180 and 180 degrees',
        },
      ],
    })
    expect(sql as unknown as jest.Mock).not.toHaveBeenCalled()
  })
})
