import { POST } from './route'
import { sql } from '@vercel/postgres'

jest.mock('@vercel/postgres', () => ({
  sql: jest.fn(),
}))

jest.mock('next/server', () => ({
  NextResponse: {
    json: jest.fn((data, options) => ({
      json: () => Promise.resolve(data),
      status: options?.status || 200,
    })),
  },
}))

function expectPosition(position: unknown) {
  expect(Array.isArray(position)).toBe(true)
  const [longitude, latitude] = position as number[]

  expect(typeof longitude).toBe('number')
  expect(typeof latitude).toBe('number')
  expect(longitude).toBeGreaterThanOrEqual(-180)
  expect(longitude).toBeLessThanOrEqual(180)
  expect(latitude).toBeGreaterThanOrEqual(-90)
  expect(latitude).toBeLessThanOrEqual(90)
}

function expectRfc7946FeatureCollection(geojson: any) {
  expect(geojson.type).toBe('FeatureCollection')
  expect(geojson.crs).toBeUndefined()
  expect(Array.isArray(geojson.features)).toBe(true)

  for (const feature of geojson.features) {
    expect(feature.type).toBe('Feature')
    expect(feature.geometry.type).toBe('Point')
    expectPosition(feature.geometry.coordinates)
    expect(feature.properties).toEqual(expect.any(Object))
  }
}

describe('GeoJSON Points API', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('should return an RFC 7946 FeatureCollection generated by PostGIS', async () => {
    const geojson = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [0, 0],
          },
          properties: {
            name: 'Null Island',
          },
        },
      ],
    }

    ;(sql as unknown as jest.Mock).mockResolvedValueOnce({
      rows: [{ geojson }],
      command: '',
      rowCount: 1,
      oid: 0,
      fields: [],
    })

    const request = new Request('http://localhost:3000/api/geojson/points', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ name: 'Null Island', lat: 0, lng: 0 }],
        latField: 'lat',
        lngField: 'lng',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()
    const sqlCall = (sql as unknown as jest.Mock).mock.calls[0]
    const sqlText = sqlCall[0].join(' ')

    expect(response.status).toBe(200)
    expectRfc7946FeatureCollection(data)
    expect(sqlText).toContain('generate_geojson')
    expect(sqlCall.slice(1)).toEqual([
      JSON.stringify([{ name: 'Null Island', lat: 0, lng: 0 }]),
      'lat',
      'lng',
      ['name'],
    ])
  })

  it('should reject point coordinates outside RFC 7946 bounds before PostGIS', async () => {
    const request = new Request('http://localhost:3000/api/geojson/points', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: [{ name: 'Invalid', lat: 91, lng: 181 }],
        latField: 'lat',
        lngField: 'lng',
        properties: ['name'],
      }),
    })

    const response = await POST(request as any)
    const data = await response.json()

    expect(response.status).toBe(400)
    expect(data).toEqual({
      error: 'Validation error occurred',
      errors: [
        {
          field: 'data[0].lat',
          message: 'lat must be between -90 and 90 degrees',
        },
        {
          field: 'data[0].lng',
          message: 'lng must be between -180 and 180 degrees',
        },
      ],
    })
    expect(sql as unknown as jest.Mock).not.toHaveBeenCalled()
  })
}
